trigger:
- tmp_integracion

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      pytest --cov=src -v -s
  displayName: 'Run Pytest'
  